export const getIngredientEmoji = (name: string): string => {
  const n = name.toLowerCase();
  if (n.includes('tomate')) return '🍅';
  if (n.includes('poulet') || n.includes('dinde') || n.includes('volaille')) return '🍗';
  if (n.includes('lait')) return '🥛';
  if (n.includes('oeuf') || n.includes('œuf')) return '🥚';
  if (n.includes('beurre')) return '🧈';
  if (n.includes('farine')) return '🌾';
  if (n.includes('sucre')) return '🧂';
  if (n.includes('sel')) return '🧂';
  if (n.includes('poivre')) return '🧂';
  if (n.includes('ail')) return '🧄';
  if (n.includes('oignon')) return '🧅';
  if (n.includes('carotte')) return '🥕';
  if (n.includes('pomme de terre') || n.includes('patate')) return '🥔';
  if (n.includes('pomme')) return '🍎';
  if (n.includes('citron')) return '🍋';
  if (n.includes('orange')) return '🍊';
  if (n.includes('banane')) return '🍌';
  if (n.includes('fraise')) return '🍓';
  if (n.includes('framboise')) return '🍇';
  if (n.includes('fromage') || n.includes('gruyère') || n.includes('parmesan') || n.includes('mozzarella')) return '🧀';
  if (n.includes('pain') || n.includes('baguette')) return '🥖';
  if (n.includes('riz')) return '🍚';
  if (n.includes('pâte') || n.includes('spaghetti') || n.includes('macaroni') || n.includes('nouille')) return '🍝';
  if (n.includes('viande') || n.includes('boeuf') || n.includes('bœuf') || n.includes('porc') || n.includes('veau') || n.includes('agneau')) return '🥩';
  if (n.includes('poisson') || n.includes('saumon') || n.includes('cabillaud') || n.includes('thon')) return '🐟';
  if (n.includes('crevette') || n.includes('gambas')) return '🦐';
  if (n.includes('huile')) return '🫒';
  if (n.includes('vinaigre')) return '🍾';
  if (n.includes('chocolat') || n.includes('cacao')) return '🍫';
  if (n.includes('miel')) return '🍯';
  if (n.includes('confiture')) return '🍓';
  if (n.includes('champignon')) return '🍄';
  if (n.includes('salade') || n.includes('laitue') || n.includes('mâche') || n.includes('roquette')) return '🥬';
  if (n.includes('épinard') || n.includes('epinard')) return '🍃';
  if (n.includes('avocat')) return '🥑';
  if (n.includes('noix') || n.includes('noisette') || n.includes('pécan')) return '🥜';
  if (n.includes('amande')) return '🌰';
  if (n.includes('eau')) return '💧';
  if (n.includes('vin')) return '🍷';
  if (n.includes('bière') || n.includes('biere')) return '🍺';
  if (n.includes('café') || n.includes('cafe')) return '☕';
  if (n.includes('thé') || n.includes('the')) return '🍵';
  if (n.includes('crème') || n.includes('creme')) return '🥛';
  if (n.includes('moutarde')) return '🌭';
  if (n.includes('mayonnaise')) return '🥚';
  if (n.includes('ketchup')) return '🍅';
  if (n.includes('sauce')) return '🥣';
  if (n.includes('herbe') || n.includes('persil') || n.includes('ciboulette') || n.includes('basilic') || n.includes('coriandre') || n.includes('thym') || n.includes('romarin')) return '🌿';
  if (n.includes('piment')) return '🌶️';
  if (n.includes('poivron')) return '🫑';
  if (n.includes('brocoli')) return '🥦';
  if (n.includes('chou')) return '🥬';
  if (n.includes('aubergine')) return '🍆';
  if (n.includes('courgette')) return '🥒';
  if (n.includes('concombre')) return '🥒';
  if (n.includes('melon')) return '🍈';
  if (n.includes('pastèque') || n.includes('pasteque')) return '🍉';
  if (n.includes('raisin')) return '🍇';
  if (n.includes('pêche') || n.includes('peche')) return '🍑';
  if (n.includes('cerise')) return '🍒';
  if (n.includes('poire')) return '🍐';
  if (n.includes('ananas')) return '🍍';
  if (n.includes('mangue')) return '🥭';
  if (n.includes('kiwi')) return '🥝';
  if (n.includes('myrtille')) return '🫐';
  if (n.includes('olive')) return '🫒';
  if (n.includes('maïs') || n.includes('mais')) return '🌽';
  if (n.includes('pois')) return '🫛';
  if (n.includes('haricot')) return '🫘';
  if (n.includes('lentille')) return '🫘';
  if (n.includes('soja')) return '🌱';
  if (n.includes('tofu')) return '🧊';
  if (n.includes('bacon') || n.includes('lard')) return '🥓';
  if (n.includes('saucisse')) return '🌭';
  if (n.includes('jambon')) return '🍖';
  if (n.includes('burger')) return '🍔';
  if (n.includes('pizza')) return '🍕';
  if (n.includes('frite')) return '🍟';
  if (n.includes('glace')) return '🍦';
  if (n.includes('gâteau') || n.includes('gateau')) return '🍰';
  if (n.includes('biscuit')) return '🍪';
  if (n.includes('croissant')) return '🥐';
  if (n.includes('crêpe') || n.includes('crepe') || n.includes('pancake')) return '🥞';
  if (n.includes('gaufre')) return '🧇';
  if (n.includes('soupe')) return '🍲';
  if (n.includes('bouillon')) return '🥣';
  if (n.includes('levure')) return '🫧';
  if (n.includes('vanille')) return '🍦';
  if (n.includes('cannelle')) return '🪵';
  
  return '🛒'; // Default emoji
};
